---
title: "Data Acquisition"
author: "Luca Mülke"
---

```{r}
library(httr)
library(jsonlite)
library(knitr)

url <- "https://api.openweathermap.org/data/2.5/weather?q=New+York,US&units=metric&appid=de7f0078e2f8223f211a60f3ee3a2b94"
response <- GET(url)

if (response$status_code == 200) {
  weather_data <- fromJSON(rawToChar(response$content))
  temperature <- weather_data$main$temp
  humidity <- weather_data$main$humidity
  wind_speed <- weather_data$wind$speed
  cloud_cover <- weather_data$clouds$all
  
  weather_table <- data.frame(
    "Temperature" = temperature,
    "Humidity" = humidity,
    "Wind Speed" = wind_speed,
    "Cloud Cover" = cloud_cover
  )

  kable(weather_table, format = "markdown")
} else {
  cat("Error:", response$status_code, response$reason)
}
```

```{r}
# WEBSCRAPING ----

# 1.0 LIBRARIES ----

library(tidyverse) # Main Package - Loads dplyr, purrr, etc.
library(rvest)     # HTML Hacking & Web Scraping
library(xopen)     # Quickly opening URLs
library(jsonlite)  # converts JSON files to R objects
library(glue)      # concatenate strings
library(stringi)   # character string/text processing
library(xml2)


html_bike_category  <- read_html("https://www.radon-bikes.de/roadbike-gravel/alu/bikegrid/")
bike_names_tbl        <- html_bike_category %>%
  
  html_nodes(css = ".a-heading--small")# %>%

names <- xml_text(bike_names_tbl)
names <- names[-c(36, 37)]
names <- names[-5]
names <- names[-4]

bike_price_tbl        <- html_bike_category %>%
  
  html_nodes(css = ".m-bikegrid__price--active")

prices <- xml_text(bike_price_tbl)
library(stringr)
prices <- str_remove(prices, " ₤")
prices <- str_remove(prices, "₤")
prices <- str_remove(prices, "₤ ")
prices <- prices[prices != ""]
library(readr)
prices_numeric <- sapply(prices, parse_number)
prices_numeric <- unname(prices_numeric)

output <- rbind(names, prices_numeric)
kable(output, format = "markdown")
```