---
title: "Data Visualization"
author: "Luca Mülke"
---
Challenge 1

```{r}
library(ggplot2)
library(tidyverse)
covid_data_tbl <- read_csv("owid-covid-data.csv")

subset_germany <- subset(covid_data_tbl, location == "Germany" | location == "United Kingdom" | location == "France" | location == "Spain" | location == "United States")

ggplot(subset_germany, aes(x = date, y = total_cases, color = location)) + geom_line() + theme_dark() + scale_x_date(date_labels = "%b-%Y", date_breaks = "1 month") + labs(title = "COVID-19 confirmed cases worldwide", subtitle = "As of 19/04/2022", y = "Cumulative Cases") + scale_y_continuous(labels = function(x) paste0(x/1000000,"M")) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6), axis.title.x=element_blank(), legend.position="bottom") + scale_color_brewer(palette="Set1")
```

Challenge 2

```{r}
library(ggplot2)
library(tidyverse)
library(scales)
covid_data_tbl <- read_csv("owid-covid-data.csv")
reduced <- covid_data_tbl[which(covid_data_tbl$date == "2022-04-16"), ]


reduced <- distinct(mutate(reduced, location = case_when(location == "United Kingdom" ~ "UK", location == "United States" ~ "USA", location == "Democratic Republic of Congo" ~ "Democratic Republic of the Congo", TRUE ~ location)))

reduced$mortality_rate <- reduced$total_deaths / reduced$population

world <- ggplot2::map_data("world")

total <- merge(world, reduced, by.x = "region", by.y = "location")

ggplot(total) + geom_map(aes(map_id = region, fill = mortality_rate), map = world) + theme_dark() + expand_limits(x = world$long, y = world$lat) + scale_fill_gradient(low = "red", high = "black", labels = percent_format()) + labs(title = "Confirmed COVID-19 deaths relative to the size of the population", subtitle = "Around 6.2 Million confimed COVID-19 deaths worldwide", caption = "Date: 04/16/2022", fill = "Mortality Rate") + theme(axis.text.x = element_blank(), axis.text.y = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank()) + borders("world", colour = "black", size = 0.1)
```