project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Tidyverse"
            file: content/01_journal/01_tidyverse.qmd
          - text: "02 Data Acquisition"
            file: content/01_journal/02_data_acquisition.qmd
          - text: "03 Data Wrangling"
            file: content/01_journal/03_data_wrangling.qmd
          - text: "04 Data Visualization"
            file: content/01_journal/04_data_visualization.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto